apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook-dev
  labels:
    env: dev
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
spec:
  project: default
  source:
    path: dev
    repoURL: https://github.com/mikhail-klimko/guestbook.git
    targetRevision: HEAD
  destination:
    name: in-cluster
    namespace: guestbook-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - PrunePropagationPolicy=foreground
      - Replace=false
      - PruneLast=false
      - Validate=true
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=false
      - ServerSideApply=true
      - RespectIgnoreDifferences=false
